version: 2.1

orbs:
  yarn: artsy/yarn@0.1.8

workflows:
  build_and_verify:
    jobs:
      - yarn/workflow-queue
      - yarn/test:
          args: -c
          requires:
            - yarn/workflow-queue
